# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 74650902b1cbad8edc924429445dc3bce9aa842df947403a79944e44683fff44d4028536857d22a59ca8bfe7d63a66586a22fa670b3215e035f7b7239dad2c3b

test:
  secret_key_base: 751dc35b88518487e7f474a416046dcc8981b77a1c0afe453c49e00b7f8f40865899b201ec77cc614b45f5fb056d5e1254f895fdb7445a4403fbeec10f5d14e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
